[project]
name = "pullrequest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygithub>=2.6.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pylint>=3.3.6",
]
